name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches-ignore: []

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      ##########################
      # Clean Workspace #
      ##########################
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: yarn install
        run: cd client/ && yarn install --ignore-scripts

      - name: Super-Linter-on-Client
        uses: docker://ghcr.io/github/super-linter:latest
        env:
          ACTIONS_RUNNER_DEBUG: false
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.base_ref }}
          DEFAULT_WORKSPACE: /client/src
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /client/
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc
          FILTER_REGEX_INCLUDE: .*src/.*
          FILTER_REGEX_EXCLUDE: .*test/.*,packages-lock.json,yarn.lock
          VALIDATE_ARM: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_CLOUDFORMATION: false
          VALIDATE_CLOJURE: false
          VALIDATE_HTML: false
          VALIDATE_CSS: false
          VALIDATE_TERRAFORM_TERRASCAN: false
          VALIDATE_JSON: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_KOTLIN: false
          VALIDATE_LATEX: false
          VALIDATE_JAVA: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_ENV: false
          VALIDATE_CSHARP: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DART: false
          VALIDATE_GO: false
          VALIDATE_GROOVY: false
          VALIDATE_LUA: false
          VALIDATE_MARKDOWN: false
          VALIDATE_OPENAPI: false
          VALIDATE_PERL: false
          VALIDATE_PHP: false
          VALIDATE_PHP_BUILTIN: false
          VALIDATE_PHP_PHPCS: false
          VALIDATE_PHP_PHPSTAN: false
          VALIDATE_PHP_PSALM: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PROTOBUF: false
          VALIDATE_POWERSHELL: false
          VALIDATE_R: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_RAKU: false
          VALIDATE_RUBY: false
          VALIDATE_YAML: false
          VALIDATE_XML: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TERRAGRUNT: false
          VALIDATE_TERRAFORM: false
          VALIDATE_TEKTON: false
          VALIDATE_SQL: false
          VALIDATE_STATES: false
          VALIDATE_SNAKEMAKE_SNAKEFMT: false
          VALIDATE_SNAKEMAKE_LINT: false

      - name: Super-Linter-on-Server
        uses: docker://github/super-linter:latest
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /server/
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc
          FILTER_REGEX_INCLUDE: .*server/.*
          FILTER_REGEX_EXCLUDE: .*test/.*
          VALIDATE_ARM: false
          VALIDATE_JSCPD: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_CLOUDFORMATION: false
          VALIDATE_CLOJURE: false
          VALIDATE_HTML: false
          VALIDATE_CSS: false
          VALIDATE_TERRAFORM_TERRASCAN: false
          VALIDATE_JSON: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_KOTLIN: false
          VALIDATE_LATEX: false
          VALIDATE_JAVA: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_ENV: false
          VALIDATE_CSHARP: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DART: false
          VALIDATE_GO: false
          VALIDATE_GROOVY: false
          VALIDATE_LUA: false
          VALIDATE_MARKDOWN: false
          VALIDATE_OPENAPI: false
          VALIDATE_PERL: false
          VALIDATE_PHP: false
          VALIDATE_PHP_BUILTIN: false
          VALIDATE_PHP_PHPCS: false
          VALIDATE_PHP_PHPSTAN: false
          VALIDATE_PHP_PSALM: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PROTOBUF: false
          VALIDATE_POWERSHELL: false
          VALIDATE_R: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_RAKU: false
          VALIDATE_RUBY: false
          VALIDATE_YAML: false
          VALIDATE_XML: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TERRAGRUNT: false
          VALIDATE_TERRAFORM: false
          VALIDATE_TEKTON: false
          VALIDATE_SQL: false
          VALIDATE_STATES: false
          VALIDATE_SNAKEMAKE_SNAKEFMT: false
          VALIDATE_SNAKEMAKE_LINT: false